{
  parserClass="com.github.chiroruxx.fishplugin.languages.FishParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Fish"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.chiroruxx.fishplugin.languages"
  psiImplPackage="com.github.chiroruxx.fishplugin.languages.impl"
  psiImplUtilClass="com.github.chiroruxx.fishplugin.languages.impl.FishPsiImplUtil"

  elementTypeHolderClass="com.github.chiroruxx.fishplugin.languages.FishTypes"
  elementTypeClass="com.github.chiroruxx.fishplugin.languages.FishElementType"
  tokenTypeClass="com.github.chiroruxx.fishplugin.languages.FishTokenType"
}

fishFile ::= item_*

private item_ ::= (sentence|CRLF)

sentence ::= COMMAND [args] [redirects]

args ::= (arg|string)+
arg ::= (CHARACTERS|ESCAPE_CHARACTERS)+

string ::= QUOTE (STRING_CHARACTERS|ESCAPE_CHARACTERS)* QUOTE

redirects ::= redirect+
redirect ::= FILE_DESCRIPTOR? REDIRECT_SYMBOLE destination
destination ::= REDIRECT_FILE|(FILE_DESCRIPTOR_SYMBOLE FILE_DESCRIPTOR)
